Ability to submit proposals using only quill
dfinity/quill pull request #134
Opened 2022-09-02 00:24 UTC by jwiegley

# Description

This changes allows one to submit motion proposal directly using quill, rather than having to involve dfx. Usage:
```
quill neuron-manage <neuron-id> --proposal-title "<title>" --proposal-summary-file <summary file path>"
```

# How Has This Been Tested?

I will test it tomorrow by submitting a motion proposal. Until then, this is marked draft.

# Checklist:

- [ ] I have made corresponding changes to the documentation in src/docs.

2022-09-07 00:07 UTC, jwiegley commented
I've used this myself to submit a proposal.

2022-09-07 00:49 UTC, jwiegley commented
That Windows failure is going to make it impossible to test using proposal contents from a file via this CI.

2022-09-23 11:57 UTC, sesi200 approved these changes, later dismissed

2022-09-23 11:59 UTC, sesi200 approved these changes, later dismissed

2022-09-23 12:30 UTC, ericswanson-dfinity requested changes
Can we have quill normalize newlines to \n format?  Also, there are lint failures.

2026-03-14 01:54 UTC, closed without merging