feat: Set neuron visibility.
dfinity/quill pull request #239
Opened 2024-08-16 15:16 UTC by daniel-wong-dfinity-org

# Description

Added `--set-visibility` flag to `quill neuron-manage`. Takes one of two possible values: `public` or `private`.

In a separate commit, updated this repo to point to a more recent commit in the ic repo.

Added a script to make the aforementioned chore easier.

# How Has This Been Tested?

Added set_visibility test.

# Checklist

- [X] I have made corresponding changes to the documentation in docs/cli-reference.
- [X] I have added corresponding integration tests.

2024-08-16 16:52 UTC, daniel-wong-dfinity-org reviewed
Some remarks that mighthopefully be helpful to reviewers.

2024-08-16 16:52 UTC, daniel-wong-dfinity-org commented on src/commands/neuron_manage.rs
> -use ic_nns_governance::pb::v1::manage_neuron::NeuronIdOrSubaccount;
I merged this into the next line. (This is not actually removed.)

2024-08-16 16:52 UTC, daniel-wong-dfinity-org commented on src/commands/neuron_manage.rs
> +        StakeMaturity, StartDissolving, StopDissolving,
The intention here is just to add SetVisibility. Thanks to our "OMG VERTICAL SPACE IS WORTH MORE THAN GOLD" mindset, this fact is highly non-obvious.

2024-08-16 16:52 UTC, daniel-wong-dfinity-org commented on src/commands/neuron_manage.rs
> +        let visibility = Some(native_visibility as i32);
re `as i32`: This happens to work because NativeVisibility has the same codes (i.e. integer values) as pb::Visibility. Is this a hack? I don't think so, but reasonable people can disagree.

2024-08-16 16:52 UTC, daniel-wong-dfinity-org commented on src/lib/format/nns_governance.rs
None of the changes in this file relate to the main objective of this PR. Rather, these changes are needed because we are pointing to a more recent commit in the ic repo. In particular, new types of proposals have been added since the last time that quill caught itself up on where the ic repo stands.

2024-08-16 17:16 UTC, adamspofford-dfinity requested changes

2024-08-16 17:16 UTC, adamspofford-dfinity commented on scripts/point-to-ic-repo-commit-id.sh
> +echo "I have changed Cargo.toml for you." >&2
Can this script be made less noisy in general?

2024-08-16 17:16 UTC, adamspofford-dfinity commented on scripts/point-to-ic-repo-commit-id.sh
> +cargo test
This is likely to fail since structs will have new fields and matched enums will have new variants.

2024-08-16 17:16 UTC, adamspofford-dfinity commented on docs/cli-reference/quill-neuron-manage.mdx
> -## Options
These are intentionally kept separate. Options take parameters and flags do not.

2024-08-16 17:16 UTC, adamspofford-dfinity commented on src/lib/format/nns_governance.rs
> +    display_set_field("wasm_memory_limit", wasm_memory_limit, &mut chunks);
These should be user-friendly names and values. See sns_root.rs for an example.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org reviewed
Thank you for the review. PTAL.

This reply might contain some duplicates. Hard to tell. GitHub seems to be handling my replies buggily. Please, bear with me.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org commented on src/lib/format/nns_governance.rs
> +                    // TODO Do something like didc decode --defs $DEFS[canister_id] $arg
I don't think that works, because this is not a request or response of some method. Rather, this is install args.

I implemented display_init_args to pretty print this.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org commented on scripts/point-to-ic-repo-commit-id.sh
> +echo "I have changed Cargo.toml for you." >&2
Please, be more specific.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org commented on src/lib/format/nns_governance.rs
> +    display_set_field("wasm_memory_limit", wasm_memory_limit, &mut chunks);
Done.

I think the original was a little more searchable, because they are _exact_ matches.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org commented on docs/cli-reference/quill-neuron-manage.mdx
> -## Options
Done.

Thanks. I now see that other quill pages also make this distinction.

# Tangent

Not sure how this distinction is useful.

Moreover, I don't think people use these terms that way. E.g. when you do `quill neuron-manage --help`, it does not break out no argument vs. with argument.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org commented on scripts/point-to-ic-repo-commit-id.sh
> +# ChatGPT helped me with this.
Done.

I really do not like being accused of plagiarism.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org commented on src/lib/format/nns_governance.rs
> +                                                "unknown visibility {visibility} ({err})???"
Done.

2024-08-20 12:44 UTC, daniel-wong-dfinity-org commented on scripts/point-to-ic-repo-commit-id.sh
> +# support --allow-unstaged-changes flag, but I'm too lazy for that.
Done.

2024-08-20 15:53 UTC, adamspofford-dfinity commented on scripts/point-to-ic-repo-commit-id.sh
> +echo "I have changed Cargo.toml for you." >&2
It just prints a lot of lines is all. I suppose it's fine.

2024-08-21 19:28 UTC, daniel-wong-dfinity-org commented on src/commands/neuron_manage.rs
> +    set_visibility: Option<NativeVisibility>,
Done.

I guess you mean in the exec function, since this line is not in a function.

2024-08-21 19:29 UTC, adamspofford-dfinity approved these changes

2024-08-21 19:29 UTC, adamspofford-dfinity approved these changes

2024-08-21 20:04 UTC, merged