Add support for generating QR codes directly.
dfinity/quill pull request #92
Opened 2021-12-19 19:43 UTC by jplevyak

Note: the print() function was being called with a Vec with non-boxed Item(s) and I couldn't figure out how to work around
that so I moved the iterator out of the generic function rather than make more intrusive changes.

PTAL and make a suggestion.

Signed-off-by: John Plevyak <jplevyak@gmail.com>

2022-01-06 18:02 UTC, jwiegley commented
I'm not too happy with the implementation here. I think it would be better from a code organization and review standpoint to introduce a Render trait, so that the top-most function can pick the `Qr` implementation to be used for printing, but nothing below would be aware of what QR codes are or how the final result will be rendered. This will also open the door naturally for JSON rendering instead of today's Candid.

Note that I did something similar for authentication in the `nitro` branch, where instead of passing around PEM data I pass an `AuthInfo` structure that allows for various identity schemes. I should back-port this part, since it conflicts often.

2022-01-06 18:03 UTC, jwiegley requested changes
I'm not too happy with the implementation here. I think it would be better from a code organization and review standpoint to introduce a Render trait, so that the top-most function can pick the Qr implementation to be used for printing, but nothing below would be aware of what QR codes are or how the final result will be rendered. This will also open the door naturally for JSON rendering instead of today's Candid.

Note that I did something similar for authentication in the nitro branch, where instead of passing around PEM data I pass an AuthInfo structure that allows for various identity schemes. I should back-port this part, since it conflicts often.

2022-01-06 19:54 UTC, jplevyak commented
The only functions effected by your suggestion are main() and exec() in src/commands/mod.rs, so it isn't as big of a win as it might be for something like AuthInfo which I imagine would involve the individual commands, not that I am opposed to the suggestion.  I could pass the trait object down to the individual commands and push the output function into them, but that doesn't seem like a win either since most functions return a Vec<Ingress> as that is the primary function of quill and doing the output in src/commands/mod.rs makes sense.

2022-01-06 21:30 UTC, jwiegley submitted a review, later dismissed

2022-01-06 21:31 UTC, jwiegley commented
Ok, you've convinced, I just wouldn't want to see a trend of "because it's easy" arguments getting added to `exec`. It doesn't feel like something exec should ever know anything about.

2022-01-07 07:48 UTC, chmllr reviewed
I must admit I'm not a big fan of QRs being built-in for the following reasons:

1. I personally probably won't use it in it's current form: my current workflow incorporates 2 steps: one send with dry-run so that I can see and validate the arguments and then piping through `qrencode` and printing a QR below. So whenever I sign a message I see human-readable candid output and a QR in one new text-editor with a small font. This works very well in a loop too, e.g. for 2-message commands like staking. But with the current vector based printing that would change, so I'd need to rewrite my workflow somehow, which I won't of course because it just works. But this is something what could be added on top of QR later maybe...
2. In contrast to keysmith, I don't think this feature would allow me to get read of `qrencode` on my AG: e.g. my principal and account id once I generated them on AG. Some people could use AG also for other wallets and need to transfer something else from AG. E.g. I also need to transfer changes to the script, which I'm developing and testing on AG.
3. (maybe it's an extension of 1. actually): this goes a bit against the Unix philosophy of making small and composable tools doing one job well. As a consequence, this feature would be also not useful to those, who want to have picture QRs or have some other different workflows. But I recognize that it could help less technical people (if they know how to make the font smaller in the terminal :D)

2022-01-07 07:48 UTC, chmllr commented on src/commands/mod.rs
> +        Command::ScannerQRCode => {
I'm not sure I understand what's happening here. What is this QR below? Also I do not see how this command can ever be called?

2022-01-07 18:05 UTC, jplevyak commented on src/commands/mod.rs
> +        Command::ScannerQRCode => {
This is the QR code for the URL to Paul's dapp for submitting the QR Ingress messages.
My workflow is to scan this QR code to load Paul's app then scan the operation I want to do, verify it in the dapp since it does the translation to Candid and then submit there.  I will add a comment.

2022-01-07 18:05 UTC, jplevyak commented on src/commands/mod.rs
> +        Command::ScannerQRCode => {
This is generated by the "quill scanner-qr-code" command.

2022-01-07 18:20 UTC, jplevyak commented
This PR was motivated by my workflow and by a request from Cédric Waldburger who asked me how to use QR codes with quill. 

I use Google Lens to transfer my principal and seed phrase.   Lens does OCR, and it is pretty accurate, but I did have to double check the result for the principal, but since it is a one off I was OK with that.

I have a bookmark on my phone for Paul's QR scanner, but I could use "quill scanner-qr-code" to load the dapp.  Normally I just run quill --qr ... and then scan with Paul's scanner and verify the Candid that his dapp outputs.

I agree that this PR is most useful for folks who are less technical and who are OK with my workflow.  I can add a feature to output an arbitrary file as QR to do the principal or account id transfer.

2022-01-07 18:45 UTC, jplevyak commented
Added command "quill qr-code [--string "..."] [--file <filename>]" to transfer principal id and/or seed phrase.

PTAL

2022-01-08 15:25 UTC, chmllr approved these changes

2022-01-08 15:25 UTC, chmllr commented on src/commands/mod.rs
> +        Command::ScannerQRCode => {
Thanks John, I see now!

2022-01-09 06:31 UTC, merged